name: task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  flutter_native_splash: ^2.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/download.png  # Make sure to add your splash image here
    - assets/images/fahad alsalem.jpg

flutter_native_splash:
  color: "#ffffff" # Background color of the splash screen
  image: assets/images/splash_image.png # Your splash image
  image_color: "#000000" # Color filter for the image (optional)
  android:fullscreen: true # Fullscreen mode
  ios:fullscreen: true # Fullscreen mode for iOS


